services:
  nn-monitor:
    container_name: nn-monitor
    hostname: neuralnet
    build:
      context: .
      dockerfile: Dockerfile
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    restart: always
